# Generated by Django 5.2.3 on 2025-06-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Munificent School', max_length=255, verbose_name='Название школы')),
                ('address', models.TextField(default="г. Алматы, ул. Достык 132, БЦ 'Прогресс', офис 401", verbose_name='Адрес')),
                ('phone', models.CharField(default='+7 (777) 123-45-67', max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(default='info@munificentschool.kz', max_length=254, verbose_name='Email')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email-уведомления')),
                ('sms_notifications', models.BooleanField(default=True, verbose_name='SMS-уведомления')),
                ('payment_reminders', models.BooleanField(default=True, verbose_name='Напоминания об оплате')),
                ('class_reminders', models.BooleanField(default=True, verbose_name='Напоминания о занятиях')),
                ('timezone', models.CharField(default='Asia/Almaty', max_length=100, verbose_name='Часовой пояс')),
                ('language', models.CharField(default='Русский', max_length=50, verbose_name='Язык системы')),
                ('currency', models.CharField(default='KZT', max_length=10, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Системные настройки',
                'verbose_name_plural': 'Системные настройки',
            },
        ),
    ]
