# Generated by Django 5.2.4 on 2025-11-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Оценка (1-5)'),
        ),
    ]
