# Generated by Django 5.2.2 on 2025-06-09 05:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название предмета')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название курса')),
                ('description', models.TextField(blank=True, verbose_name='Описание курса')),
                ('zoom_link', models.URLField(blank=True, default='https://zoom.us/j/123456789', max_length=500, null=True, verbose_name='Ссылка на Zoom')),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='courses_enrolled', to=settings.AUTH_USER_MODEL, verbose_name='Ученики')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название урока')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('time', models.TimeField(default=datetime.time(18, 0), verbose_name='Время проведения')),
                ('status', models.CharField(choices=[('пройден', 'Пройден'), ('предстоит', 'Предстоит')], default='предстоит', max_length=10, verbose_name='Статус')),
                ('recording_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на запись')),
                ('homework_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на ДЗ')),
                ('homework_text', models.TextField(blank=True, null=True, verbose_name='Текст ДЗ')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Текст вопроса')),
                ('options', models.JSONField(verbose_name='Варианты ответов')),
                ('correct_option_index', models.PositiveSmallIntegerField(verbose_name='Индекс правильного ответа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='courses.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Вопрос для теста',
                'verbose_name_plural': 'Вопросы для тестов',
            },
        ),
    ]
