# Generated by Django 5.2.4 on 2025-07-31 05:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_subject_remove_testquestion_subject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата урока'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='homework_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Д/З'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='recording_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на запись'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланирован'), ('completed', 'Проведен'), ('cancelled', 'Отменен')], default='planned', max_length=10, verbose_name='Статус урока'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время урока'),
        ),
    ]
