# Generated by Django 5.2.4 on 2025-11-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_students_lesson_date_lesson_homework_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
