# Generated by Django 5.2.4 on 2025-11-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lessoncompletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата урока'),
        ),
    ]
