# Generated by Django 5.2.2 on 2025-06-07 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL фото')),
                ('public_description', models.TextField(blank=True, verbose_name='Описание для лендинга')),
                ('public_subjects', models.CharField(blank=True, max_length=200, verbose_name='Предметы для лендинга (через запятую)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
