# Generated by Django 5.2.2 on 2025-06-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='parent_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='ФИО родителя'),
        ),
        migrations.AddField(
            model_name='profile',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон родителя'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.CharField(blank=True, max_length=200, verbose_name='Школа'),
        ),
        migrations.AddField(
            model_name='profile',
            name='student_class',
            field=models.CharField(blank=True, max_length=50, verbose_name='Класс'),
        ),
    ]
