# Generated by Django 5.2.4 on 2025-07-31 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_enrolled_courses_user_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.URLField(blank=True, null=True, verbose_name='URL аватара'),
        ),
    ]
