# Generated by Django 5.2.4 on 2025-11-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_photo_url_remove_user_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Опыт работы'),
        ),
    ]
